# Generated by Django 3.1.7 on 2021-03-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('profile_image', models.ImageField(upload_to='')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.BooleanField()),
                ('bio', models.TextField()),
                ('friends', models.ManyToManyField(to='user.User')),
            ],
        ),
    ]
