# Generated by Django 3.1.7 on 2021-03-24 10:48

import Bookord.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210324_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='additional_image_1',
            field=models.ImageField(default='media\\default\\cover', upload_to=Bookord.user.models.book_additional_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='additional_image_2',
            field=models.ImageField(default='media\\default\\cover', upload_to=Bookord.user.models.book_additional_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='additional_image_3',
            field=models.ImageField(default='media\\default\\cover', upload_to=Bookord.user.models.book_additional_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='media\\default\\cover', upload_to=Bookord.user.models.book_cover_path),
            preserve_default=False,
        ),
    ]
