# Generated by Django 3.1.7 on 2021-03-25 18:25

import Bookord.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210324_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='additional_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=Bookord.user.models.book_additional_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='additional_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=Bookord.user.models.book_additional_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='additional_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=Bookord.user.models.book_additional_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=Bookord.user.models.book_cover_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bookmarks',
            field=models.ManyToManyField(null=True, to='user.Book'),
        ),
        migrations.AlterField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(null=True, to='user.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=Bookord.user.models.user_directory_path),
        ),
    ]
