# Generated by Django 3.1.7 on 2021-03-25 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_auto_20210325_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('page_number', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.book')),
            ],
        ),
        migrations.CreateModel(
            name='Twitch',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.entry')),
                ('idea', models.TextField()),
                ('liked', models.PositiveBigIntegerField(default=0)),
            ],
            bases=('core.entry',),
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.entry')),
                ('dictionary_entry', models.URLField(default='https://www.ldoceonline.com/', max_length=1000)),
                ('mastry_score', models.PositiveIntegerField(default=0)),
            ],
            bases=('core.entry',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
        ),
    ]
