# Generated by Django 3.2.6 on 2021-08-06 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=user.models.user_directory_path)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.BooleanField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('coins', models.PositiveBigIntegerField(default=0)),
                ('bookmarks', models.ManyToManyField(blank=True, to='core.Book')),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='user.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
