# Generated by Django 3.2.6 on 2021-08-06 13:57

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=200)),
                ('page_number', models.PositiveIntegerField()),
                ('additional_info', models.TextField(blank=True)),
                ('overview', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=core.models.book_cover_path)),
                ('additional_image_1', models.ImageField(blank=True, null=True, upload_to=core.models.book_additional_path)),
                ('additional_image_2', models.ImageField(blank=True, null=True, upload_to=core.models.book_additional_path)),
                ('additional_image_3', models.ImageField(blank=True, null=True, upload_to=core.models.book_additional_path)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('page_number', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
            ],
        ),
        migrations.CreateModel(
            name='Twitch',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.entry')),
                ('idea', models.TextField()),
                ('liked', models.PositiveBigIntegerField(default=0)),
            ],
            bases=('core.entry',),
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.entry')),
                ('dictionary_entry', models.URLField(default='https://www.ldoceonline.com/', max_length=1000)),
                ('mastery_score', models.PositiveIntegerField(default=0)),
            ],
            bases=('core.entry',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
